### ISSUE TITLE
Add support for reading parameters from existing Excel model

### ISSUE THREAD

**Issue by snorfalorpagus** [jetuk/pycatchmod#5]
I have some code for this, need to commit it.

**Comment by jetuk** [comment]
Sounds good.

**Comment by jetuk** [comment]
See #8 I think this should be consistent in terms of units and not undertake conversions internally. I think this means that Cq and Q1 should not use cumecs. Generally there is a mismatch of units (m3, km3, seconds, days, etc.) in the Excel inputs.

**Comment by snorfalorpagus** [comment]
Tag #17
